Added dt_pivot_wider() and dt_pivot_longer()
TysonStanley/tidyfast pull request #7
Opened 2019-11-25 20:41 UTC by mtfairbanks

Here's my attempt at these! Thanks for walking me through the process

2019-11-27 19:31 UTC, TysonStanley commented on R/pivot_longer.R
> +#'   dt_pivot_longer(cols = c(x, y), names_to = "stuff", values_to = "things")
Add `library(data.table)` at the beginning of the examples.

2019-11-27 19:33 UTC, TysonStanley commented on R/pivot_longer.R
> +
Near the top of the function, consider adding something like:

```
if (isFALSE(is.data.table(data)))
  data <- as.data.table(data)
```

2019-11-27 19:33 UTC, TysonStanley commented on R/pivot_longer.R
> +                   # ...,
I like the idea of using `...` to be able to pass additional arguments to `melt()`.

2019-11-27 19:34 UTC, TysonStanley commented on R/pivot_wider.R
> +#'   dt_pivot_wider(names_from = stuff, values_from = things)
Add `library(data.table)` here too :)

2019-11-27 19:35 UTC, TysonStanley commented on R/pivot_wider.R
> +
I think this function is particularly helpful as I don't think `dcast()` is intuitive. Love what you've done here.

2019-11-27 19:35 UTC, TysonStanley commented on R/pivot_wider.R
> +}
This doesn't need to be repeated in both files. In fact, you could put this function in the `utils.R` file.

2019-11-27 19:39 UTC, TysonStanley requested changes
This is a fantastic start, @mtfairbanks! Thanks for putting this together. I've left some feedback if you are interested in making these adjustments. 

Another thing to consider is creating unit tests. You can see how I've done that thus far in `tidyfast` by looking in the `tests` folder. These can help make sure the functions are doing what we expect them to do in a variety of cases.

2019-11-28 18:10 UTC, mtfairbanks commented
Thanks for the suggestions! I'll try and work on some unit tests this weekend. Happy thanksgiving

2019-12-03 04:47 UTC, mtfairbanks commented
Any thoughts on the latest commits?

2019-12-03 07:58 UTC, TysonStanley commented
I like how these look, @mtfairbanks! I can totally work with this. I very much appreciate your additions here. I'll let you know when they are fully integrated into the package. 

Note that a list of the contributors (like yourself) will be highlighted in the README. Thanks again!

2019-12-03 08:02 UTC, merged